name: 'md2zhihu'
description: >
  Convert markdown to a single-file by uploading local assets.

branding:
  icon: upload-cloud
  color: green

inputs:
  pattern:
    description: 'file pattern to convert'
    required: true
    default: '**/*.md'

  output_dir:
    description: >
      dir to store converted markdown.
    required: true
    default: '_md2zhihu'

  asset_branch:
    description: >
      The branch in which assets are stored.
      This branch must NOT be removed otherwise the assets will not be accessed.
    required: true
    default: '_md2zhihu/asset'

  target_platform:
    description: >
      The platform that the converted markdown should be compatible to.

      Currently supported platforms are zhihu, wechat, weibo, simple.
      `simple` converts almost everything to images and removes most text styles.
      E.g. inline code block is converted to normal text.

    required: true
    default: 'zhihu'

outputs:
  converted_branch:
    description: "The url of the branch of converted markdowns"
    value: ${{ steps.convert.outputs.converted_branch }}
runs:
  using: "composite"
  steps:
    - name: install deps
      run: |
        npm install @mermaid-js/mermaid-cli@8.8.4
        sudo apt-get install pandoc
        sudo apt-get install graphviz
        pip3 install setuptools wheel
        pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: convert
      id: convert
      run: |
        cp -R ${{ github.action_path }} md2zhihu

        python3 -m md2zhihu \
          --repo https://github.com/${{ github.repository }}.git@${{ inputs.asset_branch }} \
          --code-width 600 \
          --platform ${{ inputs.target_platform }} \
          --md-output ${{ inputs.output_dir }}/ \
          ${{ inputs.pattern }}

        git add ${{ inputs.output_dir }}

        git \
          -c "user.name=drmingdrmer" \
          -c "user.email=drdr.xp@gmail.com" \
          commit -m "md2zhihu built"

        git push -f origin HEAD:${{ github.ref }}-md2zhihu

        echo "::set-output name=converted_branch::https://github.com/${{ github.repository }}/tree/${{ github.ref }}-md2zhihu"
      shell: bash
